spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 200MB



---
###### local ######
server:
  port: 80

spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver



---
###### test ######
server:
  port: 80

spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver


---
###### deploy ######
server:
  port: 443
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: deploy

