server:
  port: 80

spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring:
  profiles: test


