spring:
  profiles:
    active: capture

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 200MB

---
###### local ######
server:
  port: 80

spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
###### test ######
server:
  port: 80

spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:   # queryDSL의 sql이 찍힘
  org.hibernate.SQL: debug

---
###### deploy ######
server:
  port: 443
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: deploy


---
#### for capture ####
server:
  port: 443
  ssl:
    key-store: classpath:keystore/capture.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: capture