spring:
  profiles:
    active: deploy

  jpa:
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB

---
server:
  port: 80

spring:
  profiles: local

---
server:
  port: 80

spring:
  profiles: test


---
server:
  port: 443
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: deploy

